### ISSUE TITLE
Possible to add gaps?

### ISSUE THREAD

**Issue by ValentinaPeona** [vgl-hub/gfastats#44]
Hi!

Is it possible to add gaps within a contig so to split the contig into two sequences (coordinates given by the user) that will be part of the same scaffold?

Thanks for the help

Valentina

**Comment by gf777** [comment]
Please take a look at the brand new instruction for masking sequences!
https://github.com/vgl-hub/gfastats/tree/main/instructions#mask

The logic for this one is less trivial than you'd think, because gaps typically would connect segments, not be embedded in them. Therefore I introduced the idea of 'inner gaps', that is a gap that is within a segment, so the GFA segment is literally split in two, before and after the gap, as part of a path. You can check out how this looks like on this test file:
`gfastats testFiles/random1.fasta -k testFiles/random1.mask.sak -ogfa2`
Please try it out and let me know if it works for your case and does what is expected.
All the best
